### ISSUE TITLE
doom emacs 中 M-x 无法找到 netease-cloud-music 函数

### ISSUE THREAD

**Issue by Sollovin** [SpringHan/netease-cloud-music.el#5]
- 找不到 netease-cloud-music 但是找得到其他函数
- `packages.el`:
> (package! netease-music)

- `config.el`:
> (use-package! netease-music)

- 执行 M-x 时的情况：
![latest-screenshot](https://user-images.githubusercontent.com/15872396/110731753-e9bd5180-825d-11eb-94c8-354d9886a045.png)

**Comment by SpringHan** [comment]
emmm
这个插件不是我的，我的是 `netease-cloud-music` ，目前没有上 melpa 里，以后会加入的。  
目前还是需要先克隆本仓库然后从本地启用插件。
```emacs-lisp
(use-package! netease-cloud-music
   :load-path "path/to/netease-cloud-music")
```

**Comment by Sollovin** [comment]
好的，我再试试，谢谢。
