### ISSUE TITLE
separate used face attribute in `netease-cloud-music-interface-init`

### ISSUE THREAD

**Issue by lyjdwh** [SpringHan/netease-cloud-music.el#7]
Do you consider separating the used face attribute in `netease-cloud-music-interface-init` as var to support easy personal customization?

such as used `font-lock-keyword-face`, `font-lock-function-name-face`, as I have already modified them in other places, so it's not suitable to use them here.

**Comment by SpringHan** [comment]
Solved in [this commit](https://github.com/SpringHan/netease-cloud-music.el/commit/ce4a1a25ec7810951b3fdc02877112365dc9d234)
